In [1]:
import numpy as np

# ndarrayの生成

In [2]:
print('リストから変換')
l = [1,2,3,4]
print(np.array(l))

print('\n初期値1のndarray')
print(np.zeros(10))

print('\n初期値0のndarray')
print(np.ones((2,3)))

print('\n0から順番に並ぶ要素のndarray')
print(np.arange(15))

print('\nランダムのndarray')
print(np.random.randn(5))

リストから変換
[1 2 3 4]

初期値1のndarray
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

初期値0のndarray
[[1. 1. 1.]
 [1. 1. 1.]]

0から順番に並ぶ要素のndarray
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

ランダムのndarray
[-0.27599973 -0.03141455 -0.79679084 -0.34204519 -0.5809345 ]


# 次元、行数、列数

In [3]:
array = np.zeros((2,3))

print('次元を確認')
print(array.ndim)

print('\n行数、列数を確認')
print(array.shape)

print('\n行列数を変更')
array = np.arange(15)
print(array)
print(array.shape)
array = array.reshape((3,5))
print(array)
print(array.shape)

次元を確認
2

行数、列数を確認
(2, 3)

行列数を変更
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


# Bool行列作成

In [4]:
array = np.array([1,2,3,2,-1,3, -2])
print(array == 2)
print(array > 0)

print('\n要素の中に1つでもTrueがあるか')
print(array.any())
print('\n要素のすべてがTrueがどうか')
print(array.all())

[False  True False  True False False False]
[ True  True  True  True False  True False]

要素の中に1つでもTrueがあるか
True

要素のすべてがTrueがどうか
True


# 積、行列積、転置行列

In [5]:
from numpy.linalg import inv

print('元の行列')
array = np.arange(15).reshape(3,5)
print(array)

print('\n単純な積')
print(2*array)

print('\n転置行列')
print(array.T)

print('\n行列積')
print(array.dot(array.T))
print(np.dot(array, array.T))

print('\n逆行列')
array = np.arange(9).reshape(3,3)
print(inv(array.T.dot(array)))

元の行列
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

単純な積
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]

転置行列
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

行列積
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]

逆行列
[[ 3.51843721e+13 -7.03687442e+13  3.51843721e+13]
 [-7.03687442e+13  1.40737488e+14 -7.03687442e+13]
 [ 3.51843721e+13 -7.03687442e+13  3.51843721e+13]]


# 和、平均、標準偏差、分散

In [6]:
print('元の行列')
array = np.arange(15).reshape(3,5)
print(array)

print('\n配列和')
print(array.sum())

print('\n平均')
print(array.mean())

print('\n標準偏差、分散')
print(array.std())
print(array.var())

元の行列
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

配列和
105

平均
7.0

標準偏差、分散
4.320493798938574
18.666666666666668


# ファイル入出力

In [7]:
array = np.arange(15).reshape(3,5)
print(array)

print('\nファイル保存')
np.save('array', array)

print('\nファイル読み出し')
np.load('array.npy')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

ファイル保存

ファイル読み出し


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])